GET http://localhost:8080/users

###

GET http://localhost:8080/mygames/fetch/Joakim

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Hikaru", 
    "email": "grgdrdg@hitdh.com",
    "password": "idc",
    "confirmPassword": "idc"
}

###

POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Joakim", 
    "password": "secret"
}